blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

app_name = 'blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('submit_article/', views.submitarticle, name='submitarticle'),
	path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.userpostdetail, name="userpostdetail"),
	


	]

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from blog import urls
app_name = 'pages'
urlpatterns =  [
    path('', views.index, name='index'),
    path('are-aliens-demons-or-what/', views.are, name ='are'),
    path('userblog/', views.userposts, name="userposts"),
    path('intro/', views.intro, name='intro'),
    path('intro/cases/', views.introcases, name='introcases'),
    path('intro/theories/', views.introtheories, name='introtheories'),
    path('intro/brave_new_world/', views.braveneworld, name='brave_new_world'),
    path('sighting/', views.sighting, name='sighting'),
    path('fermi/', views.fermi, name='fermi'),
    path('theory/', views.theory, name='theory'),
    path('user_theories/', views.usertheories, name='usertheories'),
    path('user_theories/<int:th_id>/', views.theorydetail, name='thdetail'),
    path('user_blog_submit', views.userblog, name='userblog'),
    path('thanks/', views.thankyou, name='thanks'),
    path('user_sightings/', views.usersightings, name='usersightings'),
    path('user_sightings/<slug:st_id>/', views.sightdetail, name="stdetail"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.bpostdetail, name="bpostdetail"),
    path('userblog/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.userpostdetail, name="userpostdetail"),
    path('thanks/', views.thankyou, name='thanks'),
    #blog section
]

ufosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
]

templates/pages/bpostdetail.html
q<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class= "one"><center>{{post.title}}</center></h1>
	<p class ="one"> {{post.body}} <br><br>
	Posted by: {{post.author}} on {{post.added}} </p>
	{% endblock content %}

</body>
</html>

templates/pages/fermi.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
{% block content %}
<h1 class ="one"><center>The Fermi Paradox<center></h1>
<p class ="one">One of the most asked questions regarding intelligent life in the universe is something along the lines of "Well if aliens are real where are they all?" and it's a fair question indeed. It's something that <a href="https://en.wikipedia.org/wiki/Enrico_Fermi">Enrico Fermi</a> asked during a lunch with colleagues in 1950, and since then something along the line of "Where are they?" has been associated with or known as "The Fermi Paradox".<br> The fermi paradox can be looked at in a few ways but is generally thought as being presented as "Why is there no sign or evidence of aliens on earth or even nearby?" or "Why is it we seem to be alone in the universe?".</p>

<p class="one"><a href="https://en.wikipedia.org/wiki/Search_for_extraterrestrial_intelligence">The search for extraterrestrial intelligence</a> has essentially been going on since the invention of radio, however even earlier than this Nikola Tesla suggested that he may have received signals from Mars whilst conducting experiments with wireless electrical transmission, since then there has been many projects set up purely in the SETI and while it may be easy to become disheartened by the fact that in that time, we have received only <em>one</em> potential signal, <a href="https://en.wikipedia.org/wiki/Wow!_signal">the WOW signal</a>, declaring that there is no life in the universe is comparable to taking a glass of water from the ocean and declaring the ocean must be void of life because we see none inside the glass.
</p>

<h2 class="one">Let's break things down</h2>
<p class="one">Despite the fact we haven't really done all that much searching ourselves, nor are we by any means at all anything other than young in the grand scheme of everything, there still remains the fact that the universe itself is extremely old. Follow the chain of reasoning: we know there are billions of stars similar to our sun, and that of those stars, there are stars older than our sun and of these suns, some will contain planets similar to ours, or goldilocks planets, planets that are "just right" for life. It seems unthinkable, given the scale of the universe, that the planet earth is either <strong>extremely</strong> rare or <strong>completely</strong> unique, so we can assume that other civilizations, older than ours will have or will exist. It is also logical to assume that these civilizations will have progressed to the point of interstellar travel during some point in their evolution, even using our own models of current interstellar travel speeds, our entire galaxy could be explored within a couple of million years. So given we can reasonably assume civilizations, much older than us (billions of years) will have reached the point of interstellar travel, why have no planets near us been colonised? Why is there no evidence of this having happened in the past? <em>Where is everyone</em>.</p>

<h2 class ="one">The Drake Equation</h2>
<p class ="one">In 1961 <a href="https://en.wikipedia.org/wiki/Frank_Drake">Frank Drake</a> came up with an equation that could be used t>Drakeo estimate how many active civilizations are in our galaxy. The equation itself is a really good way of generating thought provoking conversation on ET life as it addresses the factors that need to be considered in it, but was never meant to be used or quoted as an accurate way of determining how prevalent alien life actually is. The problem lies in the fact that most of the figures used need to be estimated and we currently have no way of knowing the actual numbers to use, this means that the result of the equation is heavily dependent on how conservative the numbers used in it are and results can vary from the galaxy being teeming with life, to the galaxy being absolutely empty. It's definetly worth reading up on if you're interested in the Fermi paradox. The <a href="https://en.wikipedia.org/wiki/Drake_equation">Drake equation</a>.</p>

<h1 class="one"><center>Theories<center></h1>
<p class="one">There's a lot of theories and suggested answers to the fermi paradox and given that this is an entirely hypothetical situation there's nothing stopping you from coming up with your own ideas. I'll outline some of the more prevelant, popular and accepted answers below.</p>

<h2 class="one">Dark Forest Theory</h2>
<p class ="one">
Kill or be killed. Dark forest theory is the idea that there is indeed extraterrestrial life out there and it may even be plentiful, but we aren't able to contact these civilizations or detect signals from them because they aren't trying to be found in the first place. It's entirely possible that life out there is on the whole, hostile, and as such us sending out signals telling the universe where we are, what we look like and what our DNA looks like (<a href="https://en.wikipedia.org/wiki/Arecibo_message">Aricebo message)</a> is actually a really bad idea. Whilst the aricebo message wasn't specifically an attempt to initiate contact and more a celebration of technical achievement, many scientists, Stephen Hawkins included, have warned against contact, citing what happened to the natives when Columbus landed in america as an analogy. He also theorised that its entirely possible alien life is actually nomadic, in which case they might view us as a source of resources more so than a star trek-esque away team opportunity.</p>

<h2 class="one">Rare Earth Hypothesis</h2>
<p class ="one">
	Rare earth hyopthesis puts forward the idea that the circumstances behind our planets formation and our evolution really are just really, really unlikely to happen. Considering the size of the universe this isn't actually as far fetched as it might seem at first glance, the conditions just for life to arise is a long list alone, let alone evolution to occur. Let's have a look at some of the boxes earth ticks
	<ul>
	<li>We're inside the galaxys habitable zone</li>
	<li>Jupiters position, size and gravitational pull protects us from comets</li> 
	<li>Moons the size of ours are necessary and rare</li>
	<li>Earth is the right size to maintain atmosphere, allowing water to exist here</li>
	<li>Plate tectonics are arguably necessary and there is reason to believe earth is the only planet in our solar system with them</li>
	<li>The conditions that spur life to progress from simple bacterias to complex life are rare</li> 
   	</ul>
   	<p class="one">This list is nowhere near exahustive, but shows that it's entirely possible that the circumstances for life to evovle really are just that rare.</p>

   	<h2 class="one">They are already here</h2>
   	<p class ="one">One of my personal favourites, this covers two possibilities, alien life is already on the planet and possibly just hides in places we aren't capable or exploring like the bottom of the ocean or inside volcanoes and the fact that a lot of sightings involve water and that its also a well known fact that volcanoes often have a high number of ufo reports around them might support this.<br><br>
   	The other possibility in this category is that alien life isn't actually "alien" at all, but live amongst us unseen, its entirely possible that something lives in a dimension that exists outside of our sensory perception and is just invisible to us. There's little point trying to explain this when someone like Carl Sagan has already done so, he explains the idea of the 4th dimension in a simple concise way here: <a href="https://www.youtube.com/watch?v=iiWKq57uAlk">Carl Sagan: Flatland</a>

   	<h2 class="one">Further Reading:</h2>
   	<p class="one">The above is a small explanation of a few of the more popular answers to the paradox and hopefully acts an easily digested introduction, if you're interested in learning more I suggest starting at the <a href="https://en.wikipedia.org/wiki/Fermi_paradox">Wiki</a>, and seeing what SETI has to say about it <a href="https://www.seti.org/fermi-paradox-0">here.</a>




{% endblock content %}
</body>
</html> equation</a> is 

templates/pages/index - Copy.html
<!DOCTYPE html>
{% extends "base.html" %}

<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<div>
<body>
{% block content %}
<h1 class ="one"><center>Ghosts and Greys</center></h1>
<p class= "one"> If this is your first visit please check out our <a href="{% url 'pages:intro' %}" class="baselinks">Introduction</a> for information on this site and contact details!</p>
<p class = "one">The following articles are written and submitted by me. 
<h3 class = "one">For articles submitted by users and to submit your own ideas, post, work etc, please click <a href="{% url 'blog:index' %}">Here</a>.</h3><br>
<p class ="one">Finally, please be aware that this site is in it's early stages and whilst its main purpose revolves around archiving and collecting data I do plan on making it generally look better. The priority was getting the back-end up and running and functional so that it serves its purpose data collection wise. Please bare with me as I handle both the back end and the front end of the site. I appreciate your patience. Additionally, signup as of right now has no purpose, i've just left the links on for esae of use later, addtionally sign-up isn't required as of now, everything on the site can be interacted with anonymously and name/email fields are always optional, again the plan there is a forum and some other little features.	</p>
<p class ="one">

<h2 class="one">Latest articles:</h2><br>
{% for post in posts %}
<a href="{{post.get_absolute_url }}">
{{post.title}}&nbsp;:&nbsp;</a> {{post.body|truncatewords:10}} Posted by {{post.username}} on {{post.added}}. <br>
{% endfor %}
</p>
{% endblock content %}
</body>
</div>
</html>

templates/pages/index.html
<!DOCTYPE html>
{% extends "base.html" %}

<html>
<head>
	{% load static %}
	
	<link rel="stylesheet" href="{% static '/css/style.css' %}">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<div>
<body>
	{% block content %}
<h1 class ="one">Ghosts and Greys</h1>
<p class= "one"> If this is your first visit we have an <a href="{% url 'pages:intro' %}">Introduction</a> page, and a few other pages aimed at getting people unfamiliar to the subject up to speed.</p>

<p> Added </p>
<p class = "one">There's a <em>very</em> small subreddited associated with this site/idea at r/OnlyUFOfans as well.</p>
<p class ="one">Finally, please be aware that this site is in it's early stages and whilst its main purpose revolves around archiving and collecting data I do plan on making it generally look better. The priority was getting the back-end up and running and functional so that it serves its purpose data collection wise. Please bare with me as I handle both the back end and the front end of the site. I appreciate your patience</p>

<h2 class="one">Latest articles:</h2><br>

<a href="{% url 'pages:are' %}">Are aliens demons or what?</a> Posted by: Admin. 
</p>
<p>
{% endblock content %}
</p>
</body>
</div>
</html>

templates/pages/sighting.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block content %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<h1 class="one">Submit a sighting here!</h1>
<p class="one">Please fill out the form below to submit your sighting.
	  <form method ="post" class ="one" action ="{% url 'pages:sighting' %}">
    {% csrf_token %}
{{ form.as_p}}
<input type="Submit" value="Submit">
</form>
</p>
{% endblock content %}
</body>
</html>

templates/pages/sightingdetail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class="one"><center>Sighting submitted by user: {{sighting.name}}</center></h1>
	<p class="one">
		<h1 class="one">{{sighting.subj}}</h1>
		<h2 class="one">Details:</h2>
		{{ sighting.body }}<br>
		Sighting time: {{sighting.time_of }}
		Theory submitted by: {{sighting.name}}. (if blank user chose to remain anonymous)	
{% endblock content %}
</body>
</html>

templates/pages/sightings.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class="one"><center>Sightings of UFO/UAP by users<center></h1>


	<p class="one">
	{% for sighting in sightings %}
	<a href="{% url 'pages:stdetail' sighting.id %}">{{sighting.subj}}&nbsp;</a>:Submitted by {{sighting.name}}<br><br>
	{% empty %}
	No sightings have been added here yet :(
	{% endfor %}

</p>
{% endblock content %}
</body>
</html>

templates/pages/thankyou.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<p class="one">
	Thank you very much for submitting your theory or sighting, it has been submitted and saved and i'll review it as soon as possible and get it posted to the website, i've chose to vet posts to keep the site family friendly but if you feel the need to expedite the process please feel free to contact me. I can be found on reddit; username u/Pandammonia!<br><br>

	<a href ="{% url 'pages:index' %}">Return to home page</a>

	{% endblock content %}

</body>
</html>

templates/pages/theory.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block content %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<h1 class="one">Submit your own theory!</h1>
<p class="one">Please fill out the form below and send me theories on UFO's/UAP, they can be on any and all subjects of the phenomena and can be as out there or scientifically backed as you like. I'll sort through each and every one, categorise them and post them.
	  <form method ="post" class ="one" action ="{% url 'pages:theory' %}">
    {% csrf_token %}
{{ form.as_p}}
All emails will be kept anonymous <br>
<input type="Submit" value="Submit">
</form>
</p>
{% endblock content %}
</body>
</html>

templates/pages/theorydetail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class="one"><center>Theory submitted by user: {{theory.Name}}</center></h1>
	<p class="one">
		<h1 class="one">{{theory.Title}}</h1>
		<h2 class="one">Details:</h2>
		{{ theory.Details }}<br><br>
		Theory submitted by: {{theory.Name}}. (if blank user chose to remain anonymous)	
{% endblock content %}
</body>
</html>

templates/pages/userblogs.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class ="one"><center>User submitted posts</center></h1>
{% for post in posts %}
<a href="{{post.get_absolute_url }}">{{post.title}}</a>

Posted by {{post.username }} on {{post.added}}</h2></p><br>
{% endfor %}
{% endblock content %}

</body>
</html>

templates/pages/userblogsubmission.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block content %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<h1 class="one">Submit a blog post</h1>
<p class="one">Please fill out the form below to submit your blog post/entry
	  <form method ="post" class ="one" action ="{% url 'pages:userblog' %}">
    {% csrf_token %}
{{ form.as_p}}
<input type="Submit" value="Submit">
</form>
</p>
{% endblock content %}
</body>
</html>

templates/pages/usertheories.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{% block content %}
	<h1 class="one"><center>Theories on UAP/UFO/Aliens/'The phenomena' by users<center></h1>


	<p class="one">
	{% for theory in theories %}
	<a href="{% url 'pages:thdetail' theory.id %}">{{theory.Title}} : submitted by {{theory.Name}}</a><br><br>
	{% empty %}
	No theories have been added here yet :(
	{% endfor %}

</p>
{% endblock content %}
</body>
</html>