accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views	

app_name = 'accounts'
urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

app_name = 'blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('submit_article/', views.submitarticle, name='submitarticle'),
	path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.userpostdetail, name="userpostdetail"),
	


	]

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from blog import urls
app_name = 'pages'
urlpatterns =  [
    path('', views.index, name='index'),
    path('are-aliens-demons-or-what/', views.are, name ='are'),
    path('userblog/', views.userposts, name="userposts"),
    path('intro/', views.intro, name='intro'),
    path('intro/cases/', views.introcases, name='introcases'),
    path('intro/theories/', views.introtheories, name='introtheories'),
    path('intro/brave_new_world/', views.braveneworld, name='brave_new_world'),
    path('sighting/', views.sighting, name='sighting'),
    path('fermi/', views.fermi, name='fermi'),
    path('theory/', views.theory, name='theory'),
    path('user_theories/', views.usertheories, name='usertheories'),
    path('user_theories/<int:th_id>/', views.theorydetail, name='thdetail'),
    path('user_blog_submit', views.userblog, name='userblog'),
    path('thanks/', views.thankyou, name='thanks'),
    path('user_sightings/', views.usersightings, name='usersightings'),
    path('user_sightings/<slug:st_id>/', views.sightdetail, name="stdetail"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.bpostdetail, name="bpostdetail"),
    path('userblog/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.userpostdetail, name="userpostdetail"),
    path('thanks/', views.thankyou, name='thanks'),
    #blog section
]

ufosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
]

templates/base - Copy.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <div class="one" style="text-align: right;">
      {% if user.is_authenticated %}Hello, {{ user.get_username }}
      <a href="{% url 'accounts:logout' %}" class="baselinks">Logout</a> 
      {% else %}
      <a href="{% url 'accounts:login' %}"class="baselinks">Login</a> 
      <a href="{% url 'accounts:register' %}"class="baselinks">Register</a><br><br>
      {% endif %}
      </div>
        <div class ="one" style="text-align: left;">
        <a href="{% url 'pages:index' %}" class="baselinks">Home</a>    
        <a href="{% url 'pages:intro' %}" style="padding: 0 0 0 20px;" class="baselinks">Introduction</a>
        <a href="{% url 'pages:introcases' %}" style="padding: 0 0 0 20px;" class ="baselinks">Cases</a>        
        <a href="{% url 'pages:introtheories' %}" style="padding: 0 0 0 20px;" class="baselinks">Theories</a>
        <a href="{% url 'pages:fermi' %}" style="padding: 0 0 0 20px;" class="baselinks">Fermi</a>
        <a href="{% url 'pages:brave_new_world' %}" style="padding: 0 0 0 20px;" class="baselinks">Brave New World</a><br>
        <a href="{% url 'pages:usersightings' %}" style="padding: 0 0 0 0px;"class="baselinks">User submitted sightings</a>
        <a href="{% url 'pages:sighting' %}" style="padding: 0 0 0 20px;" class="baselinks">Submit a sighting</a><br>
        <a href="{% url 'pages:usertheories' %}" style="padding: 10 0 0 10px;" class="baselinks">User submitted theories</a>
        <a href="{% url 'pages:theory' %}" style="padding: 0 0 0 20px;" class="baselinks">Submit a theory</a><br>
        <a href="{% url 'blog:index' %}" style="padding: 0 0 0 0px;" class="baselinks">User submitted posts</a>
        <a href="{% url 'blog:submitarticle' %}" style="padding: 0 0 0 46px;" class="baselinks">Submit an article</a><br>
        
        
        </p>
      </div>
    {% block content %}{% endblock content %}
    </body>
    </html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    


    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
  <section class="banner">
  <div>
    <center><img src="{% static 'ggbannerbetter1080.jpg' %}" alt="banner"></center>
  </div>
  <div class="navbar">
  <a href="{% url 'pages:index' %}" class="baselinks">Home</a>
  <a href="{% url 'pages:intro' %}">Introduction</a>
  <div class="dropdown">
    <button class="dropbtn">Basics
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'pages:introcases' %}">Cases</a>
      <a href="{% url 'pages:introtheories' %}">Theories</a>
      <a href="{% url 'pages:fermi' %}">Fermi</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">In-depth
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'pages:brave_new_world' %}">Brave new world</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">Sightings
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'pages:usersightings' %}">User submitted sightings</a>
      <a href="{% url 'pages:sighting' %}">Submit a sighting</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">Theories
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'pages:usertheories' %}">User submitted theories</a>
      <a href="{% url 'pages:theory' %}">Submit a theory</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">User Posts
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'blog:index' %}">User submitted posts</a>
      <a href="{% url 'blog:submitarticle' %}">Submit an article</a>
    </div>
  </div>
    <div class="dropdown">
    <button class="dropbtn">Users
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      {% if user.is_authenticated %}
      <a href="{% url 'accounts:logout' %}" class="baselinks">Logout</a>
      {% else %}
      <a href="{% url 'accounts:login' %}"class="baselinks">Login</a>
      <a href="{% url 'accounts:register' %}"class="baselinks">Register</a>
      {% endif %}
    </div>
  </div>
</div>
<div class="one" style="text-align: right;">
        <p class ="one">{% if user.is_authenticated %}Hello, {{ user.get_username }}. <a href="{% url 'accounts:logout' %}" class="baselinks">Logout</a>.</p>
        {% endif %}
    </section>

    {% block content %}{% endblock content %}
    </body>
    </html>